// flow-typed signature: 4e8996a1a24edecf38f8f11acc6b0bb6
// flow-typed version: <<STUB>>/babel-node_v^6.5.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-node/message' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-node/message.js' {
  declare module.exports: $Exports<'babel-node/message'>;
}
