// flow-typed signature: b620f4c3316de785bb292e44f97ca366
// flow-typed version: <<STUB>>/babel-preset-node_v^5.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-node/index' {
  declare module.exports: $Exports<'babel-preset-node'>;
}
declare module 'babel-preset-node/index.js' {
  declare module.exports: $Exports<'babel-preset-node'>;
}
