// flow-typed signature: 1ffef08698001c5a48ee16e58052a1cd
// flow-typed version: <<STUB>>/file-system_v^2.2.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-system/file-system' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-system/file-system.js' {
  declare module.exports: $Exports<'file-system/file-system'>;
}
