// flow-typed signature: 39a731f736c12319acf0e7d62c220a42
// flow-typed version: <<STUB>>/gaze_v^1.1.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gaze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gaze' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gaze/lib/gaze' {
  declare module.exports: any;
}

declare module 'gaze/lib/helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gaze/lib/gaze.js' {
  declare module.exports: $Exports<'gaze/lib/gaze'>;
}
declare module 'gaze/lib/helper.js' {
  declare module.exports: $Exports<'gaze/lib/helper'>;
}
