// flow-typed signature: 207b207f25f499a892fc6ccf08fe9cb7
// flow-typed version: <<STUB>>/lodash-deep_v^2.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-deep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-deep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-deep/config/karma.conf' {
  declare module.exports: any;
}

declare module 'lodash-deep/lodash-deep' {
  declare module.exports: any;
}

declare module 'lodash-deep/lodash-deep.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-deep/config/karma.conf.js' {
  declare module.exports: $Exports<'lodash-deep/config/karma.conf'>;
}
declare module 'lodash-deep/lodash-deep.js' {
  declare module.exports: $Exports<'lodash-deep/lodash-deep'>;
}
declare module 'lodash-deep/lodash-deep.min.js' {
  declare module.exports: $Exports<'lodash-deep/lodash-deep.min'>;
}
