// flow-typed signature: a0dc59db994d355de02c1a7dfa96265d
// flow-typed version: <<STUB>>/message_v^0.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'message'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'message' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'message/app' {
  declare module.exports: any;
}

declare module 'message/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'message/app.js' {
  declare module.exports: $Exports<'message/app'>;
}
declare module 'message/server.js' {
  declare module.exports: $Exports<'message/server'>;
}
