// flow-typed signature: af8e661e97cd987b4930b3c21e20e285
// flow-typed version: <<STUB>>/mssql_v^4.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mssql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mssql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mssql/lib/base' {
  declare module.exports: any;
}

declare module 'mssql/lib/cli' {
  declare module.exports: any;
}

declare module 'mssql/lib/connectionstring' {
  declare module.exports: any;
}

declare module 'mssql/lib/datatypes' {
  declare module.exports: any;
}

declare module 'mssql/lib/isolationlevel' {
  declare module.exports: any;
}

declare module 'mssql/lib/msnodesqlv8' {
  declare module.exports: any;
}

declare module 'mssql/lib/table' {
  declare module.exports: any;
}

declare module 'mssql/lib/tedious' {
  declare module.exports: any;
}

declare module 'mssql/lib/udt' {
  declare module.exports: any;
}

declare module 'mssql/msnodesqlv8' {
  declare module.exports: any;
}

declare module 'mssql/tedious' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mssql/index' {
  declare module.exports: $Exports<'mssql'>;
}
declare module 'mssql/index.js' {
  declare module.exports: $Exports<'mssql'>;
}
declare module 'mssql/lib/base.js' {
  declare module.exports: $Exports<'mssql/lib/base'>;
}
declare module 'mssql/lib/cli.js' {
  declare module.exports: $Exports<'mssql/lib/cli'>;
}
declare module 'mssql/lib/connectionstring.js' {
  declare module.exports: $Exports<'mssql/lib/connectionstring'>;
}
declare module 'mssql/lib/datatypes.js' {
  declare module.exports: $Exports<'mssql/lib/datatypes'>;
}
declare module 'mssql/lib/isolationlevel.js' {
  declare module.exports: $Exports<'mssql/lib/isolationlevel'>;
}
declare module 'mssql/lib/msnodesqlv8.js' {
  declare module.exports: $Exports<'mssql/lib/msnodesqlv8'>;
}
declare module 'mssql/lib/table.js' {
  declare module.exports: $Exports<'mssql/lib/table'>;
}
declare module 'mssql/lib/tedious.js' {
  declare module.exports: $Exports<'mssql/lib/tedious'>;
}
declare module 'mssql/lib/udt.js' {
  declare module.exports: $Exports<'mssql/lib/udt'>;
}
declare module 'mssql/msnodesqlv8.js' {
  declare module.exports: $Exports<'mssql/msnodesqlv8'>;
}
declare module 'mssql/tedious.js' {
  declare module.exports: $Exports<'mssql/tedious'>;
}
