// flow-typed signature: 4cb34f77ef729cad1675014566e274b2
// flow-typed version: <<STUB>>/n-readlines_v^0.2.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'n-readlines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'n-readlines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'n-readlines/example' {
  declare module.exports: any;
}

declare module 'n-readlines/readlines_test' {
  declare module.exports: any;
}

declare module 'n-readlines/readlines' {
  declare module.exports: any;
}

// Filename aliases
declare module 'n-readlines/example.js' {
  declare module.exports: $Exports<'n-readlines/example'>;
}
declare module 'n-readlines/readlines_test.js' {
  declare module.exports: $Exports<'n-readlines/readlines_test'>;
}
declare module 'n-readlines/readlines.js' {
  declare module.exports: $Exports<'n-readlines/readlines'>;
}
