// flow-typed signature: ab4b61997176865191be441cfb71ce74
// flow-typed version: <<STUB>>/node-ipc_v^9.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-ipc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-ipc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-ipc/dao/client' {
  declare module.exports: any;
}

declare module 'node-ipc/dao/socketServer' {
  declare module.exports: any;
}

declare module 'node-ipc/entities/Defaults' {
  declare module.exports: any;
}

declare module 'node-ipc/entities/EventParser' {
  declare module.exports: any;
}

declare module 'node-ipc/node-ipc' {
  declare module.exports: any;
}

declare module 'node-ipc/services/IPC' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-ipc/dao/client.js' {
  declare module.exports: $Exports<'node-ipc/dao/client'>;
}
declare module 'node-ipc/dao/socketServer.js' {
  declare module.exports: $Exports<'node-ipc/dao/socketServer'>;
}
declare module 'node-ipc/entities/Defaults.js' {
  declare module.exports: $Exports<'node-ipc/entities/Defaults'>;
}
declare module 'node-ipc/entities/EventParser.js' {
  declare module.exports: $Exports<'node-ipc/entities/EventParser'>;
}
declare module 'node-ipc/node-ipc.js' {
  declare module.exports: $Exports<'node-ipc/node-ipc'>;
}
declare module 'node-ipc/services/IPC.js' {
  declare module.exports: $Exports<'node-ipc/services/IPC'>;
}
