// flow-typed signature: 7b456b47f65dcfac570b29b5a74f1d42
// flow-typed version: <<STUB>>/psnode_v^0.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'psnode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'psnode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'psnode/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'psnode/index' {
  declare module.exports: $Exports<'psnode'>;
}
declare module 'psnode/index.js' {
  declare module.exports: $Exports<'psnode'>;
}
declare module 'psnode/lib/index.js' {
  declare module.exports: $Exports<'psnode/lib/index'>;
}
