// flow-typed signature: dd896a0287d857b48d1917d2d3f664ff
// flow-typed version: <<STUB>>/step-profiler_v^0.3.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'step-profiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'step-profiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'step-profiler/profiler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'step-profiler/profiler.js' {
  declare module.exports: $Exports<'step-profiler/profiler'>;
}
