// flow-typed signature: f5cb5e4eccf19da5cb91becc9e24e755
// flow-typed version: <<STUB>>/sync-request_v^4.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sync-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sync-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sync-request/browser' {
  declare module.exports: any;
}

declare module 'sync-request/lib/find-port' {
  declare module.exports: any;
}

declare module 'sync-request/lib/json-buffer/index' {
  declare module.exports: any;
}

declare module 'sync-request/lib/legacy-worker' {
  declare module.exports: any;
}

declare module 'sync-request/lib/nc-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sync-request/browser.js' {
  declare module.exports: $Exports<'sync-request/browser'>;
}
declare module 'sync-request/index' {
  declare module.exports: $Exports<'sync-request'>;
}
declare module 'sync-request/index.js' {
  declare module.exports: $Exports<'sync-request'>;
}
declare module 'sync-request/lib/find-port.js' {
  declare module.exports: $Exports<'sync-request/lib/find-port'>;
}
declare module 'sync-request/lib/json-buffer/index.js' {
  declare module.exports: $Exports<'sync-request/lib/json-buffer/index'>;
}
declare module 'sync-request/lib/legacy-worker.js' {
  declare module.exports: $Exports<'sync-request/lib/legacy-worker'>;
}
declare module 'sync-request/lib/nc-server.js' {
  declare module.exports: $Exports<'sync-request/lib/nc-server'>;
}
