// flow-typed signature: 547cd1778a612e41f21b5563bf1deb64
// flow-typed version: <<STUB>>/tedious_v^2.1.5/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tedious'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tedious' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tedious/benchmarks/common' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/index' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/many-result-rows' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/nvarchar-large' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/nvarchar-small' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/varbinary-4' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/varbinary-huge' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/varbinary-large' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/query/varbinary-small' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/token-parser/colmetadata-token' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/token-parser/done-token' {
  declare module.exports: any;
}

declare module 'tedious/benchmarks/token-parser/simple-tokens' {
  declare module.exports: any;
}

declare module 'tedious/lib/all-headers' {
  declare module.exports: any;
}

declare module 'tedious/lib/bulk-load' {
  declare module.exports: any;
}

declare module 'tedious/lib/collation' {
  declare module.exports: any;
}

declare module 'tedious/lib/connection' {
  declare module.exports: any;
}

declare module 'tedious/lib/connector' {
  declare module.exports: any;
}

declare module 'tedious/lib/data-type' {
  declare module.exports: any;
}

declare module 'tedious/lib/debug' {
  declare module.exports: any;
}

declare module 'tedious/lib/errors' {
  declare module.exports: any;
}

declare module 'tedious/lib/guid-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/instance-lookup' {
  declare module.exports: any;
}

declare module 'tedious/lib/library' {
  declare module.exports: any;
}

declare module 'tedious/lib/login7-payload' {
  declare module.exports: any;
}

declare module 'tedious/lib/message-io' {
  declare module.exports: any;
}

declare module 'tedious/lib/metadata-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/ntlm-payload' {
  declare module.exports: any;
}

declare module 'tedious/lib/packet' {
  declare module.exports: any;
}

declare module 'tedious/lib/prelogin-payload' {
  declare module.exports: any;
}

declare module 'tedious/lib/request' {
  declare module.exports: any;
}

declare module 'tedious/lib/rpcrequest-payload' {
  declare module.exports: any;
}

declare module 'tedious/lib/sender' {
  declare module.exports: any;
}

declare module 'tedious/lib/special-stored-procedure' {
  declare module.exports: any;
}

declare module 'tedious/lib/sqlbatch-payload' {
  declare module.exports: any;
}

declare module 'tedious/lib/tds-versions' {
  declare module.exports: any;
}

declare module 'tedious/lib/tedious' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/colmetadata-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/done-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/env-change-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/infoerror-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/loginack-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/nbcrow-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/order-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/returnstatus-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/returnvalue-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/row-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/sspi-token-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/stream-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/token-stream-parser' {
  declare module.exports: any;
}

declare module 'tedious/lib/token/token' {
  declare module.exports: any;
}

declare module 'tedious/lib/tracking-buffer/bigint' {
  declare module.exports: any;
}

declare module 'tedious/lib/tracking-buffer/writable-tracking-buffer' {
  declare module.exports: any;
}

declare module 'tedious/lib/transaction' {
  declare module.exports: any;
}

declare module 'tedious/lib/transient-error-lookup' {
  declare module.exports: any;
}

declare module 'tedious/lib/value-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tedious/benchmarks/common.js' {
  declare module.exports: $Exports<'tedious/benchmarks/common'>;
}
declare module 'tedious/benchmarks/index.js' {
  declare module.exports: $Exports<'tedious/benchmarks/index'>;
}
declare module 'tedious/benchmarks/query/many-result-rows.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/many-result-rows'>;
}
declare module 'tedious/benchmarks/query/nvarchar-large.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/nvarchar-large'>;
}
declare module 'tedious/benchmarks/query/nvarchar-small.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/nvarchar-small'>;
}
declare module 'tedious/benchmarks/query/varbinary-4.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/varbinary-4'>;
}
declare module 'tedious/benchmarks/query/varbinary-huge.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/varbinary-huge'>;
}
declare module 'tedious/benchmarks/query/varbinary-large.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/varbinary-large'>;
}
declare module 'tedious/benchmarks/query/varbinary-small.js' {
  declare module.exports: $Exports<'tedious/benchmarks/query/varbinary-small'>;
}
declare module 'tedious/benchmarks/token-parser/colmetadata-token.js' {
  declare module.exports: $Exports<'tedious/benchmarks/token-parser/colmetadata-token'>;
}
declare module 'tedious/benchmarks/token-parser/done-token.js' {
  declare module.exports: $Exports<'tedious/benchmarks/token-parser/done-token'>;
}
declare module 'tedious/benchmarks/token-parser/simple-tokens.js' {
  declare module.exports: $Exports<'tedious/benchmarks/token-parser/simple-tokens'>;
}
declare module 'tedious/lib/all-headers.js' {
  declare module.exports: $Exports<'tedious/lib/all-headers'>;
}
declare module 'tedious/lib/bulk-load.js' {
  declare module.exports: $Exports<'tedious/lib/bulk-load'>;
}
declare module 'tedious/lib/collation.js' {
  declare module.exports: $Exports<'tedious/lib/collation'>;
}
declare module 'tedious/lib/connection.js' {
  declare module.exports: $Exports<'tedious/lib/connection'>;
}
declare module 'tedious/lib/connector.js' {
  declare module.exports: $Exports<'tedious/lib/connector'>;
}
declare module 'tedious/lib/data-type.js' {
  declare module.exports: $Exports<'tedious/lib/data-type'>;
}
declare module 'tedious/lib/debug.js' {
  declare module.exports: $Exports<'tedious/lib/debug'>;
}
declare module 'tedious/lib/errors.js' {
  declare module.exports: $Exports<'tedious/lib/errors'>;
}
declare module 'tedious/lib/guid-parser.js' {
  declare module.exports: $Exports<'tedious/lib/guid-parser'>;
}
declare module 'tedious/lib/instance-lookup.js' {
  declare module.exports: $Exports<'tedious/lib/instance-lookup'>;
}
declare module 'tedious/lib/library.js' {
  declare module.exports: $Exports<'tedious/lib/library'>;
}
declare module 'tedious/lib/login7-payload.js' {
  declare module.exports: $Exports<'tedious/lib/login7-payload'>;
}
declare module 'tedious/lib/message-io.js' {
  declare module.exports: $Exports<'tedious/lib/message-io'>;
}
declare module 'tedious/lib/metadata-parser.js' {
  declare module.exports: $Exports<'tedious/lib/metadata-parser'>;
}
declare module 'tedious/lib/ntlm-payload.js' {
  declare module.exports: $Exports<'tedious/lib/ntlm-payload'>;
}
declare module 'tedious/lib/packet.js' {
  declare module.exports: $Exports<'tedious/lib/packet'>;
}
declare module 'tedious/lib/prelogin-payload.js' {
  declare module.exports: $Exports<'tedious/lib/prelogin-payload'>;
}
declare module 'tedious/lib/request.js' {
  declare module.exports: $Exports<'tedious/lib/request'>;
}
declare module 'tedious/lib/rpcrequest-payload.js' {
  declare module.exports: $Exports<'tedious/lib/rpcrequest-payload'>;
}
declare module 'tedious/lib/sender.js' {
  declare module.exports: $Exports<'tedious/lib/sender'>;
}
declare module 'tedious/lib/special-stored-procedure.js' {
  declare module.exports: $Exports<'tedious/lib/special-stored-procedure'>;
}
declare module 'tedious/lib/sqlbatch-payload.js' {
  declare module.exports: $Exports<'tedious/lib/sqlbatch-payload'>;
}
declare module 'tedious/lib/tds-versions.js' {
  declare module.exports: $Exports<'tedious/lib/tds-versions'>;
}
declare module 'tedious/lib/tedious.js' {
  declare module.exports: $Exports<'tedious/lib/tedious'>;
}
declare module 'tedious/lib/token/colmetadata-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/colmetadata-token-parser'>;
}
declare module 'tedious/lib/token/done-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/done-token-parser'>;
}
declare module 'tedious/lib/token/env-change-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/env-change-token-parser'>;
}
declare module 'tedious/lib/token/infoerror-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/infoerror-token-parser'>;
}
declare module 'tedious/lib/token/loginack-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/loginack-token-parser'>;
}
declare module 'tedious/lib/token/nbcrow-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/nbcrow-token-parser'>;
}
declare module 'tedious/lib/token/order-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/order-token-parser'>;
}
declare module 'tedious/lib/token/returnstatus-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/returnstatus-token-parser'>;
}
declare module 'tedious/lib/token/returnvalue-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/returnvalue-token-parser'>;
}
declare module 'tedious/lib/token/row-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/row-token-parser'>;
}
declare module 'tedious/lib/token/sspi-token-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/sspi-token-parser'>;
}
declare module 'tedious/lib/token/stream-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/stream-parser'>;
}
declare module 'tedious/lib/token/token-stream-parser.js' {
  declare module.exports: $Exports<'tedious/lib/token/token-stream-parser'>;
}
declare module 'tedious/lib/token/token.js' {
  declare module.exports: $Exports<'tedious/lib/token/token'>;
}
declare module 'tedious/lib/tracking-buffer/bigint.js' {
  declare module.exports: $Exports<'tedious/lib/tracking-buffer/bigint'>;
}
declare module 'tedious/lib/tracking-buffer/writable-tracking-buffer.js' {
  declare module.exports: $Exports<'tedious/lib/tracking-buffer/writable-tracking-buffer'>;
}
declare module 'tedious/lib/transaction.js' {
  declare module.exports: $Exports<'tedious/lib/transaction'>;
}
declare module 'tedious/lib/transient-error-lookup.js' {
  declare module.exports: $Exports<'tedious/lib/transient-error-lookup'>;
}
declare module 'tedious/lib/value-parser.js' {
  declare module.exports: $Exports<'tedious/lib/value-parser'>;
}
