// flow-typed signature: 0eabf928af992d4c6a8fd011fae88b4a
// flow-typed version: <<STUB>>/wait.for_v^0.6.6/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait.for'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait.for' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait.for/parallel-tests' {
  declare module.exports: any;
}

declare module 'wait.for/tests' {
  declare module.exports: any;
}

declare module 'wait.for/waitfor-demo' {
  declare module.exports: any;
}

declare module 'wait.for/waitfor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait.for/parallel-tests.js' {
  declare module.exports: $Exports<'wait.for/parallel-tests'>;
}
declare module 'wait.for/tests.js' {
  declare module.exports: $Exports<'wait.for/tests'>;
}
declare module 'wait.for/waitfor-demo.js' {
  declare module.exports: $Exports<'wait.for/waitfor-demo'>;
}
declare module 'wait.for/waitfor.js' {
  declare module.exports: $Exports<'wait.for/waitfor'>;
}
