// flow-typed signature: 0f0ca6dcc0e81043204c2dd7a2aeca05
// flow-typed version: <<STUB>>/wdio-dot-reporter_v0.0.9/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-dot-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-dot-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-dot-reporter/build/reporter' {
  declare module.exports: any;
}

declare module 'wdio-dot-reporter/lib/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-dot-reporter/build/reporter.js' {
  declare module.exports: $Exports<'wdio-dot-reporter/build/reporter'>;
}
declare module 'wdio-dot-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'wdio-dot-reporter/lib/reporter'>;
}
