// flow-typed signature: 6529724b8c6ddbae33f6250de92fb878
// flow-typed version: <<STUB>>/wdio-mocha-framework_v^0.5.12/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-mocha-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-mocha-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-mocha-framework/build/adapter' {
  declare module.exports: any;
}

declare module 'wdio-mocha-framework/lib/adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-mocha-framework/build/adapter.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/build/adapter'>;
}
declare module 'wdio-mocha-framework/lib/adapter.js' {
  declare module.exports: $Exports<'wdio-mocha-framework/lib/adapter'>;
}
