// flow-typed signature: 1e2dfe50078eecc747645b6013983a9a
// flow-typed version: <<STUB>>/xml-formatter_v^1.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xml-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xml-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xml-formatter/browser/xml-formatter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xml-formatter/browser/xml-formatter.js' {
  declare module.exports: $Exports<'xml-formatter/browser/xml-formatter'>;
}
declare module 'xml-formatter/index' {
  declare module.exports: $Exports<'xml-formatter'>;
}
declare module 'xml-formatter/index.js' {
  declare module.exports: $Exports<'xml-formatter'>;
}
