// flow-typed signature: 6eec91d27ca1417edcd4d41c11d5f592
// flow-typed version: <<STUB>>/@wdio/cli_v^5.7.15/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@wdio/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@wdio/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@wdio/cli/bin/wdio' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/commands/repl' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/config' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/index' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/interface' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/launcher' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/run' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/setup' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/utils' {
  declare module.exports: any;
}

declare module '@wdio/cli/build/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module '@wdio/cli/bin/wdio.js' {
  declare module.exports: $Exports<'@wdio/cli/bin/wdio'>;
}
declare module '@wdio/cli/build/commands/repl.js' {
  declare module.exports: $Exports<'@wdio/cli/build/commands/repl'>;
}
declare module '@wdio/cli/build/config.js' {
  declare module.exports: $Exports<'@wdio/cli/build/config'>;
}
declare module '@wdio/cli/build/index.js' {
  declare module.exports: $Exports<'@wdio/cli/build/index'>;
}
declare module '@wdio/cli/build/interface.js' {
  declare module.exports: $Exports<'@wdio/cli/build/interface'>;
}
declare module '@wdio/cli/build/launcher.js' {
  declare module.exports: $Exports<'@wdio/cli/build/launcher'>;
}
declare module '@wdio/cli/build/run.js' {
  declare module.exports: $Exports<'@wdio/cli/build/run'>;
}
declare module '@wdio/cli/build/setup.js' {
  declare module.exports: $Exports<'@wdio/cli/build/setup'>;
}
declare module '@wdio/cli/build/utils.js' {
  declare module.exports: $Exports<'@wdio/cli/build/utils'>;
}
declare module '@wdio/cli/build/watcher.js' {
  declare module.exports: $Exports<'@wdio/cli/build/watcher'>;
}
