// flow-typed signature: db0d8d3993706d65786925b1cc0f8148
// flow-typed version: <<STUB>>/@wdio/local-runner_v^5.7.15/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@wdio/local-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@wdio/local-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@wdio/local-runner/build/constants' {
  declare module.exports: any;
}

declare module '@wdio/local-runner/build/index' {
  declare module.exports: any;
}

declare module '@wdio/local-runner/build/repl' {
  declare module.exports: any;
}

declare module '@wdio/local-runner/build/replQueue' {
  declare module.exports: any;
}

declare module '@wdio/local-runner/build/run' {
  declare module.exports: any;
}

declare module '@wdio/local-runner/build/transformStream' {
  declare module.exports: any;
}

declare module '@wdio/local-runner/build/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@wdio/local-runner/build/constants.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/constants'>;
}
declare module '@wdio/local-runner/build/index.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/index'>;
}
declare module '@wdio/local-runner/build/repl.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/repl'>;
}
declare module '@wdio/local-runner/build/replQueue.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/replQueue'>;
}
declare module '@wdio/local-runner/build/run.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/run'>;
}
declare module '@wdio/local-runner/build/transformStream.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/transformStream'>;
}
declare module '@wdio/local-runner/build/worker.js' {
  declare module.exports: $Exports<'@wdio/local-runner/build/worker'>;
}
