// flow-typed signature: 571b1339b4bc02cbd20a357d92698315
// flow-typed version: <<STUB>>/@wdio/sync_v^5.7.13/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@wdio/sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@wdio/sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@wdio/sync/build/constants' {
  declare module.exports: any;
}

declare module '@wdio/sync/build/executeHooksWithArgs' {
  declare module.exports: any;
}

declare module '@wdio/sync/build/index' {
  declare module.exports: any;
}

declare module '@wdio/sync/build/runFnInFiberContext' {
  declare module.exports: any;
}

declare module '@wdio/sync/build/utils' {
  declare module.exports: any;
}

declare module '@wdio/sync/build/wrapCommand' {
  declare module.exports: any;
}

// Filename aliases
declare module '@wdio/sync/build/constants.js' {
  declare module.exports: $Exports<'@wdio/sync/build/constants'>;
}
declare module '@wdio/sync/build/executeHooksWithArgs.js' {
  declare module.exports: $Exports<'@wdio/sync/build/executeHooksWithArgs'>;
}
declare module '@wdio/sync/build/index.js' {
  declare module.exports: $Exports<'@wdio/sync/build/index'>;
}
declare module '@wdio/sync/build/runFnInFiberContext.js' {
  declare module.exports: $Exports<'@wdio/sync/build/runFnInFiberContext'>;
}
declare module '@wdio/sync/build/utils.js' {
  declare module.exports: $Exports<'@wdio/sync/build/utils'>;
}
declare module '@wdio/sync/build/wrapCommand.js' {
  declare module.exports: $Exports<'@wdio/sync/build/wrapCommand'>;
}
